version: '1.0'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3000:3000
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    env_file:
      - .env.prod
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
    networks:
      - common-network
    ports:
      - 3307:${DB_PORT} # 显式映射 MySQL 端口
  redis-container:
    image: redis
    volumes:
      - ${REDIS_DATA_PATH}:/data
    networks:
      - common-network
    ports:
      - 6379:${RD_PORT} # 显式映射 Redis 端口
networks:
  common-network:
    driver: bridge
