name: Deploy to Remote Server

on:
  push:
    branches:
      - master # 触发条件，可以根据需要修改

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/web_server/fs-admin # 进入项目目录
            git pull # 拉取最新代码
            docker compose down --rmi all # 停止并删除所有容器
            docker compose --env-file .env.prod up
